# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mylinks.methods


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True, verbose_name='Link URL')),
                ('embed', models.TextField(blank=True, default=None, null=True, verbose_name='Embed HTML')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Title')),
                ('source', models.TextField(blank=True, default=None, null=True, verbose_name='Source HTML')),
            ],
            options={
                'verbose_name': 'Web Page',
                'verbose_name_plural': 'Web Page',
            },
            bases=(models.Model, mylinks.methods.Page),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Site Host Name')),
                ('name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('brand', models.TextField(blank=True, default=None, null=True, verbose_name='Site Brand')),
            ],
            options={
                'verbose_name': ' Site',
                'verbose_name_plural': ' Site',
            },
            bases=(models.Model, mylinks.methods.Site),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mylinks.Site'),
        ),
    ]
