# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mylinks.methods


class Migration(migrations.Migration):

    dependencies = [
        ('mylinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True, verbose_name='Link URL')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Title')),
                ('site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mylinks.Site')),
            ],
            options={
                'verbose_name': 'Web Link',
                'verbose_name_plural': 'Web Link',
            },
            bases=(models.Model, mylinks.methods.Link),
        ),
    ]
