# Generated by Django 2.2.4 on 2019-09-22 23:52

from django.db import migrations, models
import mylinks.models.methods


class Migration(migrations.Migration):

    dependencies = [
        ('mylinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(db_index=True, max_length=400, unique=True, validators=[mylinks.models.methods.is_ascii], verbose_name='Link URL'),
        ),
    ]
