# Generated by Django 2.2.4 on 2019-09-05 15:29

from django.db import migrations, models
import django.db.models.deletion
import mylinks.models.methods


class Migration(migrations.Migration):

    dependencies = [
        ('mylinks', '0002_auto_20190906_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mylinks.Link')),
                ('html', models.TextField(blank=True, default=None, null=True, verbose_name='Embed HTML')),
                ('data', models.TextField(blank=True, default=None, null=True, verbose_name='Embed JSON')),
                ('source', models.TextField(blank=True, default=None, null=True, verbose_name='Page Source HTML')),
            ],
            options={
                'verbose_name': 'Web Embed',
                'verbose_name_plural': 'Web Embed',
            },
            bases=('mylinks.link', models.Model, mylinks.models.methods.Embed),
        ),
    ]
